### ISSUE TITLE
Invalid type cast bug in video surface handle

### ISSUE THREAD

**Issue by EroticDevelopment** [EroticDevelopment/GuideMe#33]
In some cases the video surface handle is an integer and it other cases it's a long. This needs properly parsed rather than type-casted to a long. Relevant log lines:
```
ERROR MainShell - VLC intialisation error java.lang.Integer cannot be cast to java.lang.Long
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
at org.guideme.guideme.ui.CompositeVideoSurface.getCompositeHandle(CompositeVideoSurface.java:45)
at org.guideme.guideme.ui.CompositeVideoSurface.<init>(CompositeVideoSurface.java:26)
at org.guideme.guideme.ui.MainShell.createShell(MainShell.java:478)
at org.guideme.guideme.App.main(App.java:113)
```

**Comment by EroticDevelopment** [comment]
This issue was unfortunately not resolved due to an accidental revert of a file. This will be resolved in the next release.
