### ISSUE TITLE
Unable to start on linux mint

### ISSUE THREAD

**Issue by rtsgua** [EroticDevelopment/GuideMe#34]
I'm on Linux Mint 20.2 (running X11), and every time on startup the application crashes.

Java: `openjdk 11.0.11 2021-04-20`
GuideMe version: both `v0.4.3` and `v0.4.4`

I'm getting this on terminal (relevant snippet):

```sh
14:44:38.473 [main] TRACE org.guideme.guideme.ui.MainShell - Enter addControlListener
14:44:38.474 [main] TRACE org.guideme.guideme.ui.MainShell - Exit addControlListener
14:44:38.475 [main] TRACE org.guideme.guideme.ui.MainShell - Enter addControlListener
14:44:38.476 [main] TRACE org.guideme.guideme.ui.MainShell - Exit addControlListener
14:44:38.476 [main] TRACE org.guideme.guideme.ui.MainShell - Enter addControlListener
14:44:38.476 [main] TRACE org.guideme.guideme.ui.MainShell - Exit addControlListener
14:44:38.478 [main] TRACE org.guideme.guideme.ui.MainShell - Exit createShell
14:44:38.478 [threadMetronome] TRACE org.guideme.guideme.ui.MetronomePlayer - MetronomePlayer run start 
14:44:38.479 [main] ERROR org.guideme.guideme.ui.MainShell -  get form fields null
java.lang.NullPointerException: null
	at org.guideme.guideme.ui.MainShell.getFormFields(MainShell.java:2730) [GuideMe.jar:?]
	at org.guideme.guideme.ui.MainShell.displayPage(MainShell.java:2884) [GuideMe.jar:?]
	at org.guideme.guideme.ui.MainShell.createShell(MainShell.java:843) [GuideMe.jar:?]
	at org.guideme.guideme.App.main(App.java:113) [GuideMe.jar:?]
14:44:38.488 [main] DEBUG org.guideme.guideme.MainLogic - displayPage PagePassed start
14:44:38.488 [main] DEBUG org.guideme.guideme.MainLogic - displayPage Flags 
14:44:38.489 [main] TRACE org.guideme.guideme.ui.MetronomePlayer - MetronomePlayer Stop 
14:44:38.489 [main] DEBUG org.guideme.guideme.ui.MainShell - MainShell stopVideo null

(SWT:16885): Gtk-CRITICAL **: 14:44:38.499: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(SWT:16885): Gtk-CRITICAL **: 14:44:38.512: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(SWT:16885): Gtk-CRITICAL **: 14:44:38.519: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
14:44:38.521 [main] ERROR org.guideme.guideme.ui.MainShell -  get form fields null
java.lang.NullPointerException: null
	at org.guideme.guideme.ui.MainShell.getFormFields(MainShell.java:2730) [GuideMe.jar:?]
	at org.guideme.guideme.ui.MainShell.runJscript(MainShell.java:2666) [GuideMe.jar:?]
	at org.guideme.guideme.MainLogic.displayPage(MainLogic.java:151) [GuideMe.jar:?]
	at org.guideme.guideme.MainLogic.displayPage(MainLogic.java:103) [GuideMe.jar:?]
	at org.guideme.guideme.ui.MainShell.displayPage(MainShell.java:2885) [GuideMe.jar:?]
	at org.guideme.guideme.ui.MainShell.createShell(MainShell.java:843) [GuideMe.jar:?]
	at org.guideme.guideme.App.main(App.java:113) [GuideMe.jar:?]

(SWT:16885): Gtk-CRITICAL **: 14:44:38.530: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(SWT:16885): Gtk-CRITICAL **: 14:44:38.536: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(SWT:16885): Gdk-WARNING **: 14:44:38.542: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
14:44:38.540 [AWT-EventQueue-0] DEBUG org.guideme.guideme.scripting.Jscript - Page: start

```

**Comment by hiss-remi** [comment]
This may be a GTK issue. Searching for "gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar" found me [this](https://bugs.eclipse.org/bugs/show_bug.cgi?id=538000) page talking about the same error, although no one mentioned the application actually crashing.

It's also reported as fixed with newer version of GTK3, so hopefully this is working for rtsgua now.

**Comment by esranonff** [comment]
@rtsgua - did you ever get anywhere with this?

I suspect we may need to wait for @EroticDevelopment to release a new version that is compatible with more recent Java setups, but I don't know if this is still actively maintained?

**Comment by djarbz** [comment]
> @rtsgua - did you ever get anywhere with this?
> 
> I suspect we may need to wait for @EroticDevelopment to release a new version that is compatible with more recent Java setups, but I don't know if this is still actively maintained?

Do you think it is a GTK issue or a Java issue?
Is there a known-working version of Java that I can downgrade to?
