### ISSUE TITLE
Won't launch on Fedora 37

### ISSUE THREAD

**Issue by djarbz** [EroticDevelopment/GuideMe#43]
Program Log
```
11:22:12.704 [main] TRACE org.guideme.guideme.App - Enter main
11:22:12.726 [main] ERROR org.guideme.guideme.App - GuideMe Version - 0.4.5
11:22:12.728 [main] DEBUG org.guideme.guideme.settings.AppSettings - AppSettings userDir: /mnt/porn/other/Games/GuideMe-v0.4.5-Linux.64-bit
11:22:12.729 [main] DEBUG org.guideme.guideme.settings.AppSettings - AppSettings userHome: /home/austin
11:22:12.729 [main] DEBUG org.guideme.guideme.settings.AppSettings - AppSettings userName: austin
11:22:12.730 [main] DEBUG org.guideme.guideme.settings.AppSettings - AppSettings fileSeparator: /
11:22:12.730 [main] DEBUG org.guideme.guideme.settings.AppSettings - AppSettings settingsLocation: data/settings.properties
11:22:14.344 [main] TRACE org.guideme.guideme.App - test for vlc: true
11:22:14.348 [main] TRACE org.guideme.guideme.App - create main shell
11:22:14.400 [main] DEBUG org.guideme.guideme.settings.GuideSettings - GuideSettings appSettings.getDataDirectory(): .\Guides
11:22:14.401 [main] DEBUG org.guideme.guideme.settings.GuideSettings - GuideSettings dataDirectory: data/
11:22:14.401 [main] DEBUG org.guideme.guideme.settings.GuideSettings - GuideSettings appSettings.getFileSeparator(): /
11:22:14.402 [main] DEBUG org.guideme.guideme.settings.GuideSettings - GuideSettings GuideId: startup
11:22:14.402 [main] DEBUG org.guideme.guideme.settings.GuideSettings - GuideSettings filename: data/startup.state
11:22:14.441 [main] TRACE org.guideme.guideme.settings.GuideSettings - GuideSettings scriptVariables
11:22:14.444 [main] TRACE org.guideme.guideme.settings.GuideSettings - GuideSettings scriptVariables scope
11:22:14.446 [main] TRACE org.guideme.guideme.settings.GuideSettings - GuideSettings saveSettings filename: data/startup.state
11:22:14.448 [main] TRACE org.guideme.guideme.settings.GuideSettings - GuideSettings saveSettings file exists 
11:22:14.463 [main] TRACE org.guideme.guideme.settings.GuideSettings - GuideSettings saveSettings scriptVariables
11:22:14.465 [main] TRACE org.guideme.guideme.settings.GuideSettings - GuideSettings saveSettings scope
11:22:14.595 [main] TRACE org.guideme.guideme.settings.GuideSettings - GuideSettings saveSettings save file: data/startup.state
11:22:14.695 [main] INFO  org.guideme.guideme.MainLogic - MainLogic getMainLogic songPath jar:file:/mnt/porn/other/Games/GuideMe-v0.4.5-Linux.64-bit/GuideMe.jar!/tick.wav
11:22:15.000 [main] TRACE org.guideme.guideme.App - create shell
11:22:15.001 [main] TRACE org.guideme.guideme.ui.MainShell - Enter createShell
11:22:15.001 [main] TRACE org.guideme.guideme.ui.MainShell - Get appSettings
11:22:15.009 [main] TRACE org.guideme.guideme.ui.MainShell - Get userSettings
11:22:15.059 [main] TRACE org.guideme.guideme.ui.MainShell - display
11:22:15.059 [main] TRACE org.guideme.guideme.ui.MainShell - shell
11:22:15.082 [main] TRACE org.guideme.guideme.ui.MainShell - shell add listener
11:22:15.086 [main] TRACE org.guideme.guideme.ui.MainShell - key filter
11:22:15.104 [main] TRACE org.guideme.guideme.ui.DebugShell - Enter createShell

(SWT:274259): Gtk-WARNING **: 11:22:15.360: Negative content width -17 (allocation 1, extents 9x9) while allocating gadget (node entry, owner GtkEntry)

(SWT:274259): Gtk-WARNING **: 11:22:15.360: Negative content width -17 (allocation 1, extents 9x9) while allocating gadget (node entry, owner GtkEntry)

(SWT:274259): Gtk-CRITICAL **: 11:22:15.416: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(SWT:274259): Gtk-CRITICAL **: 11:22:15.416: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(SWT:274259): Gtk-CRITICAL **: 11:22:15.416: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(SWT:274259): Gtk-WARNING **: 11:22:15.417: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node scrollbar, owner GtkScrollbar)

(SWT:274259): Gtk-CRITICAL **: 11:22:15.417: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(SWT:274259): Gtk-WARNING **: 11:22:15.418: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node scrollbar, owner GtkScrollbar)

(SWT:274259): Gtk-CRITICAL **: 11:22:15.418: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(SWT:274259): Gtk-WARNING **: 11:22:15.419: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node scrollbar, owner GtkScrollbar)

(SWT:274259): Gtk-CRITICAL **: 11:22:15.419: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
11:22:15.455 [main] TRACE org.guideme.guideme.ui.DebugShell - Exit createShell
Exception in thread "main" org.eclipse.swt.SWTError: No more handles [Browser style SWT.MOZILLA and Java system property org.eclipse.swt.browser.DefaultType=mozilla are not supported with GTK 3 as XULRunner is not ported for GTK 3 yet]
        at org.eclipse.swt.SWT.error(Unknown Source)
        at org.eclipse.swt.browser.MozillaDelegate.<init>(Unknown Source)
        at org.eclipse.swt.browser.Mozilla.create(Unknown Source)
        at org.eclipse.swt.browser.Browser.<init>(Unknown Source)
        at org.guideme.guideme.ui.MainShell.createShell(MainShell.java:403)
        at org.guideme.guideme.App.main(App.java:113)
```

System Information
```
cat /etc/os-release 
NAME="Fedora Linux"
VERSION="37 (KDE Plasma)"
ID=fedora
VERSION_ID=37
PLATFORM_ID="platform:f37"
PRETTY_NAME="Fedora Linux 37 (KDE Plasma)"
VARIANT="KDE Plasma"
VARIANT_ID=kde
```
```
echo $XDG_SESSION_TYPE
x11
```

**Comment by esranonff** [comment]
duplicate of #34 ?
